erDiagram
    Periodo {
        int Periodo_ID PK
        smallint Periodo_Anio
        tinyint Periodo_MesNumero
        date Periodo_Fecha
    }
    Sucursal {
        int Sucursal_ID PK
        nvarchar Sucursal_Nombre UK
        nvarchar Sucursal_Region
    }
    Destino {
        int Destino_ID PK
        nvarchar Destino_Nombre UK
        nvarchar Destino_Rubro
        nvarchar Destino_TipoOperacion
    }
    FactCarteraPrestamo {
        int FactCarteraPrestamo_ID PK
        int FactCarteraPrestamo_SucursalID FK
        int FactCarteraPrestamo_PeriodoID FK
        int FactCarteraPrestamo_CantidadPrestamos
        decimal FactCarteraPrestamo_ValorRD
    }
    FactAreaFinanciada {
        int FactAreaFinanciada_ID PK
        int FactAreaFinanciada_SucursalID FK
        int FactAreaFinanciada_PeriodoID FK
        decimal FactAreaFinanciada_Tareas
        decimal FactAreaFinanciada_ValorRD
    }
    FactDesembolsoCobro {
        int FactDesembolsoCobro_ID PK
        int FactDesembolsoCobro_SucursalID FK
        int FactDesembolsoCobro_PeriodoID FK
        decimal FactDesembolsoCobro_DesembolsosRD
        decimal FactDesembolsoCobro_CobrosRD
    }
    FactMontoDestino {
        int FactMontoDestino_ID PK
        int FactMontoDestino_DestinoID FK
        int FactMontoDestino_PeriodoID FK
        decimal FactMontoDestino_ValoresRD
        int FactMontoDestino_Beneficiados
    }
